/**
 * @fileoverview gRPC-Web generated client stub for cctv
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: cctv.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require("grpc-web");

const proto = {};
proto.cctv = require("./cctv_pb.js");

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cctv.MonitoringClient = function (hostname, credentials, options) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cctv.MonitoringPromiseClient = function (hostname, credentials, options) {
  if (!options) options = {};
  options.format = "text";

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, "");
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cctv.Empty,
 *   !proto.cctv.Image>}
 */
const methodDescriptor_Monitoring_GetImage = new grpc.web.MethodDescriptor(
  "/cctv.Monitoring/GetImage",
  grpc.web.MethodType.UNARY,
  proto.cctv.Empty,
  proto.cctv.Image,
  /**
   * @param {!proto.cctv.Empty} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.cctv.Image.deserializeBinary
);

/**
 * @param {!proto.cctv.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cctv.Image)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cctv.Image>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cctv.MonitoringClient.prototype.getImage = function (
  request,
  metadata,
  callback
) {
  return this.client_.rpcCall(
    this.hostname_ + "/cctv.Monitoring/GetImage",
    request,
    metadata || {},
    methodDescriptor_Monitoring_GetImage,
    callback
  );
};

/**
 * @param {!proto.cctv.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cctv.Image>}
 *     Promise that resolves to the response
 */
proto.cctv.MonitoringPromiseClient.prototype.getImage = function (
  request,
  metadata
) {
  return this.client_.unaryCall(
    this.hostname_ + "/cctv.Monitoring/GetImage",
    request,
    metadata || {},
    methodDescriptor_Monitoring_GetImage
  );
};

export default proto.cctv;
